#-----------------------------------------------------------------------
# ?? ??
#-----------------------------------------------------------------------
server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #### DB INFO
  #-----------------------------------------------------------------------
  # API LOG - MYSQL(??)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/mega?&serverTimezone=Asia/Seoul
    username: mega
    password: mega1234
    mapper-locations: classpath:/mapper/**/*.xml



