#-----------------------------------------------------------------------
# ?? ??
#-----------------------------------------------------------------------
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #### DB INFO
  #-----------------------------------------------------------------------
  # API LOG - MYSQL(??)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/webmovies?&serverTimezone=Asia/Seoul
    username: webmovies
    password: rnjsdPwl1@
    mapper-locations: classpath:/mapper/**/*.xml



